### PR TITLE
feat: keep existing highlights and notes, and add sort by chapter progress

### LINKED ISSUE #91: [Feature Request] Append to highlight note instead of overwriting.
Painfully realised that currently when importing highlights, the entire highlights page is generated fresh.
This means that any caret references, edits to highlight notes are broken / overwritten on each import.

This limits the usefulness of the plugin quite severely as the highlights page can only then ever be used as a visual reference to read and remind ones self (or copy and paste 😵), and therefore not truly integrated into the Obsidian / Zettelkasten note making workflow.

I think the simplest solution around this would be to simply append new highlights / notes to the highlights file instead of overwriting the whole file completely with a fresh import. From memory the Kindle highlights plugin works this way.

Is it realistic to look into something like this? Would be immensely appreciated.
I want to help, but my programming chops are probably not going to do much.

I'd be happy to update and extend the documentation if needs be though.

### PR DESCRIPTION
**Pull request by rsletta**
This PR adds support for keeping existing highlights and notes, and a new setting to sort highlights by chapter progress, rather than annotation creation date. 

The implementation uses a simple approach using the existing files, rather than creating unnecessary complexity by introducing some sort of state management. It uses the bookmark id from the Kobo db as highlight markers. On transformation to markdown, the plugin checks to see if the highlight already exist, and if it does that, it injects the existing markdown, rather than the new. By using the bookmark id in the highlight marker, we are able to handle them as separate blocks. Using comments as highlight markers makes them invisible in read mode.

Tests are refactored to include the highlight markers, and a new test is introduced to test handling of existing highlights.

README is updated with information regarding the changes.

Fixes #91

### CODE REVIEW

**Comment by OGKevin** [comment]
My Typos 😩 🙈 
Thx for fixing them!

---

This is a nice solution, thanks for the PR!

A few questions:

- What if a bookmark goes missing from the DB? I think it would be nice to at least mark the extracted note as stale/deleted. And the user can than decide what to do with it.
- I need to check out the code and test, but are highlight markers visible in edit mode in Obsidian? Do you need to explicitly enable source mode? If this is the case, than I think we need to document this as well.
- Is the same bookmark ID re-used by kobo if you update an existing highlight? If so, instead of re-using the existing content in the .md file, we might want to replace that with what has been extracted from the DB.

Based on the above, I suggest to create 2 markers, and inner marker and an outer marker:
```
%%START-c5b2637d-ddaf-4f15-9a81-dd701e0ad8fe%%
<user can type what they want here>
%%START-EXTRACED-BOOKMARK-c5b2637d-ddaf-4f15-9a81-dd701e0ad8fe%%
<text from db, 100% managed by plugin>
%%END-EXTRACED-BOOKMARK-c5b2637d-ddaf-4f15-9a81-dd701e0ad8fe%%
<user can type what they want here>
%%END-c5b2637d-ddaf-4f15-9a81-dd701e0ad8fe%%
```
This way
1. We extract the whole block
2. Keep the highlight up to date or mark as stale
3. Still preserve user content

wdyt?

**Comment by rsletta** [comment]
Thanks for the feedback.

The markers are visible in regular edit mode(Live preview).
image

I will investigate if the id is kept on edits, or if a new is created. I'll also see if I can find a good solution of handling it, and also the one regarding removed highlights. In the current implementation, a removed bookmark would mean it would be removed from the file. I'm not foreign to consider your suggestion. I'll get back to you when I have something. ☺️👍

**Comment by rsletta** [comment]
Sorry about the slow progress. Between my job and family obligations, I haven't had the time or energy to work on this yet. I just wanted to give an update, so you don't think I've abandoned it. 🙄 Hopefully things will calm a bit down towards the summer, so I can get it done. 👍

**Comment by OGKevin** [comment]
@rsletta anything change re your availability? No rush, just checking in.

**Comment by rsletta** [comment]
I so sorry for not working faster. There has been no time to sit down and get back into this yet, even though I hoped I would be able to in my summer holiday. I have to prioritize family time first, and then it hasn't been much left. I can step away if I'm blocking progress, but I do intend to finish what I've started, if there isn't a rush. Sorry for the slow progress. 😕

**Comment by OGKevin** [comment]
FYI @rsletta: https://github.com/OGKevin/obsidian-kobo-highlights-import/issues/266#issuecomment-1863348197

**Comment by rsletta** [comment]
Thank's for the heads up. I'm really sorry for dropping the ball on this, not delivering as promised.

**Comment by OGKevin** [comment]
Screenshot 2024-01-11 at 12 48 49
Screenshot 2024-01-11 at 12 48 53

---

I've also added a test case where the highlight is outdated, while having a custom note.

**Comment by OGKevin** [comment]
```

> obsidian-kobo-highlights-importer-plugin@1.5.4 test
> mocha



  HighlightService
    Sample Content
      Sample Bookmark with no annotation
        ✔ fromMaptoMarkdown with date
        ✔ fromMaptoMarkdown without date
        ✔ fromMaptoMarkdown with callouts
        ✔ fromMaptoMarkdown with callouts and date
        ✔ fromMaptoMarkdown with custom callouts
        ✔ fromMaptoMarkdown with custom callouts and date
      Sample Bookmark with annotation
        ✔ fromMaptoMarkdown with date
        ✔ fromMaptoMarkdown without date
        ✔ fromMaptoMarkdown with callouts
        ✔ fromMaptoMarkdown with callouts and date
        ✔ fromMaptoMarkdown with custom callouts
        ✔ fromMaptoMarkdown with custom callouts and date
      Sample Bookmark with annotation, with existing highlights and added notes
        ✔ fromMaptoMarkdown with existing file
      Sample Bookmark with annotation, with outdated existing highlights and added notes
        ✔ fromMaptoMarkdown with existing file
    Sample Content Missing
      Sample Bookmark linked to missing content
bookmark seems to link to a non existing content: missing-content-id
        ✔ fromMaptoMarkdown with date
    with multiple content
      ✔ getAllHighlight
      ✔ createHighlightFromBookmark e7f8f92d-38ca-4556-bab8-a4d902e9c430
      ✔ createHighlightFromBookmark d40c9071-993f-4f1f-ae53-594847d9fd27
      ✔ createHighlightFromBookmark 3408844d-65a6-4d23-9d99-8f189ca07d0b
      ✔ createHighlightFromBookmark c0d92aca-e4bb-476a-8131-ee0c0c21ced5

  Repository
    ✔ getAllBookmark (46ms)
    ✔ getBookmarkById null
    ✔ getBookmarkById not null
    ✔ getAllContent
    ✔ getContentByContentId
    ✔ getContentByContentId no results
    ✔ getAllContentByBookTitle (61ms)

  template
    ✔ applyTemplateTransformations default
    ✔ applyTemplateTransformations default
    ✔ applyTemplateTransformations with front matter


  30 passing (161ms)
```

**Pull request merged**
